#!/usr/bin/env node
// SPDX-License-Identifier: MIT — Copyright (c) 2026 Paul Richeson
// §DX-01e — a doc anchor names a SYMBOL; the line number is a refreshable hint.
//
// THE DEFECT THIS RETIRES. The docs pointed into `play.html` with bare line
// numbers — "`execBits` (`21722`)", "`_addVoidPressure` (`26578`)". Every HTML edit
// shifts them, and nothing ever noticed: of 14 anchors sampled when this row opened,
// NINE pointed at unrelated code (`22104` had become a prof-bonus line, `31618` an
// aurosBlueprintKnown branch). A rotted anchor is worse than none — it reads as
// authoritative and sends the next session to the wrong place. So nearly every §VM-01
// row ends with the same tax: "re-grep the anchors before the next edit — they drift."
//
// THE CONVENTION. Write the anchor as one token:
//
//     `symbol@1234`        e.g. `execBits@21785` · `const WORLD_DB@6279`
//
// The SYMBOL is the pointer — any literal substring of the line you mean. The number
// is a cached convenience so a human can jump straight there. That split is the same
// lesson §DX-02e and §DX-02f both landed on: **pin the property, never the generated
// coordinate.** A line number is generated by every edit above it; the symbol is not.
//
// WHAT THE GATE FAILS ON — and deliberately what it does not:
//   FAIL  a DEAD anchor: the symbol is nowhere in the HTML. That is a real stale
//         pointer — the code was renamed or deleted and the doc still names it.
//   WARN  a STALE hint: the symbol resolves, the cached number drifted. Not a failure,
//         because failing here would just re-create the per-increment tax this row
//         exists to remove — `npm run anchors:fix` refreshes every one mechanically.
//
// Usage:
//   node scripts/resolve-anchors.js                # audit every doc; exit 1 on dead anchors
//   node scripts/resolve-anchors.js --fix          # rewrite stale cached numbers in place
//   node scripts/resolve-anchors.js --legacy       # count the un-migrated bare `NNNNN` anchors
//   node scripts/resolve-anchors.js execBits       # lookup: where does this symbol live NOW?
//   node scripts/resolve-anchors.js --selftest     # prove each phase catches a plant
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const HTML = path.join(ROOT, 'play.html');

// Docs that may carry anchors. Directories are walked for *.md.
const DOC_ROOTS = ['.', 'docs'];
const SKIP_DIRS = new Set(['node_modules', '.git', 'test-results', 'playwright-report',
  'archive', 'r2h', 'ledger', 'build', 'vendor', 'sources', 'importers']);

// `symbol@1234` — symbol is any run of non-backtick chars, number is the cached hint.
const ANCHOR_RE = /`([^`\n]{1,100}?)@(\d{2,6})`/g;
// The legacy form this row retires: a bare backticked 4–5 digit number.
const LEGACY_RE = /`(\d{4,5})`/g;
// The docs have to SHOW the convention. `symbol@1234` is the documented placeholder and
// is skipped everywhere — otherwise --fix would happily re-point the example itself (the
// word "symbol" does occur in the game file, so it resolves, which is worse than dead).

// ── doc discovery ─────────────────────────────────────────────────────────────
function docFiles() {
  const out = [];
  const walk = (dir, depth) => {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      if (ent.name.startsWith('.')) continue;
      const p = path.join(dir, ent.name);
      if (ent.isDirectory()) {
        if (SKIP_DIRS.has(ent.name) || depth >= 4) continue;
        walk(p, depth + 1);
      } else if (ent.name.endsWith('.md')) out.push(p);
    }
  };
  for (const r of DOC_ROOTS) {
    const dir = path.join(ROOT, r);
    if (!fs.existsSync(dir)) continue;
    if (r === '.') {
      for (const ent of fs.readdirSync(dir, { withFileTypes: true }))
        if (ent.isFile() && ent.name.endsWith('.md')) out.push(path.join(dir, ent.name));
    } else walk(dir, 0);
  }
  return out.sort();
}

// ── resolution ────────────────────────────────────────────────────────────────
// An anchor may name another repo file: `src/js/wbapi-server.js:seededNext@1147`. Default
// target is the game file. Returns {lines, target, sym} or null if the file is missing.
const FILE_QUALIFIED = /^([\w./-]+\.(?:js|mjs|html|md)):(.+)$/;
function targetFor(sym, defaultLines, cache) {
  const m = FILE_QUALIFIED.exec(sym);
  if (!m) return { lines: defaultLines, sym };
  const [, file, rest] = m;
  if (!cache.has(file)) {
    const p = path.join(ROOT, file);
    cache.set(file, fs.existsSync(p) ? fs.readFileSync(p, 'utf8').split('\n') : null);
  }
  return { lines: cache.get(file), sym: rest, file };
}

const PLACEHOLDER = /^(?:symbol|sym|path\/to\/file\.js:symbol)$/;
const isPlaceholder = sym => PLACEHOLDER.test(sym);

// Every 1-indexed line of the target that contains `sym` as a literal substring — but
// at an IDENTIFIER BOUNDARY where the symbol's own edge is a word char. Without that,
// renaming `XP_BY_TIER` → `XP_BY_TIER_RETIRED` would still "resolve" the old anchor by
// prefix, and a rename is exactly the case this gate exists to catch.
const WORD = /[A-Za-z0-9_$]/;
function resolve(lines, sym) {
  const hits = [];
  if (!lines || !sym) return hits;
  const headBound = WORD.test(sym[0]);
  const tailBound = WORD.test(sym[sym.length - 1]);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    let at = line.indexOf(sym);
    while (at !== -1) {
      const before = at > 0 ? line[at - 1] : '';
      const after = line[at + sym.length] || '';
      if (!(headBound && WORD.test(before)) && !(tailBound && WORD.test(after))) { hits.push(i + 1); break; }
      at = line.indexOf(sym, at + 1);
    }
  }
  return hits;
}

function nearest(hits, cached) {
  return hits.reduce((a, b) => (Math.abs(b - cached) < Math.abs(a - cached) ? b : a));
}

// Classify every anchor in every doc. Returns {dead[], stale[], generic[], fresh}.
function audit(docs, lines) {
  const dead = [], stale = [], generic = [], fresh = [];
  const cache = new Map();
  for (const { file, text } of docs) {
    const docLines = text.split('\n');
    for (let i = 0; i < docLines.length; i++) {
      let m; ANCHOR_RE.lastIndex = 0;
      while ((m = ANCHOR_RE.exec(docLines[i]))) {
        const [, sym, numStr] = m;
        if (isPlaceholder(sym)) continue;
        const cached = Number(numStr);
        const t = targetFor(sym, lines, cache);
        const hits = resolve(t.lines, t.sym);
        const at = { file, docLine: i + 1, sym, cached, hits };
        if (!hits.length) dead.push(at);
        else if (hits.includes(cached)) fresh.push(at);
        else stale.push(at);
        if (hits.length > 25) generic.push(at);
      }
    }
  }
  return { dead, stale, generic, fresh };
}

// Rewrite stale cached numbers in place. Returns the number of tokens rewritten.
function fix(docs, lines) {
  let changed = 0;
  const cache = new Map();
  for (const doc of docs) {
    const next = doc.text.replace(ANCHOR_RE, (whole, sym, numStr) => {
      if (isPlaceholder(sym)) return whole;
      const t = targetFor(sym, lines, cache);
      const hits = resolve(t.lines, t.sym);
      if (!hits.length) return whole;                       // dead — never guess
      const cached = Number(numStr);
      if (hits.includes(cached)) return whole;
      changed++;
      return '`' + sym + '@' + nearest(hits, cached) + '`';
    });
    if (next !== doc.text) { fs.writeFileSync(doc.file, next); doc.text = next; }
  }
  return changed;
}

function legacyCounts(docs) {
  return docs.map(d => {
    LEGACY_RE.lastIndex = 0;
    return { file: d.file, count: (d.text.match(LEGACY_RE) || []).length };
  }).filter(r => r.count).sort((a, b) => b.count - a.count);
}

const rel = f => path.relative(ROOT, f);

// ── selftest — each phase must catch a planted defect ─────────────────────────
function selftest() {
  const tmp = fs.mkdtempSync(path.join(require('os').tmpdir(), 'anchors-'));
  // A 40-line stand-in for the HTML: `knownSymbol` lives at line 12 and nowhere else.
  const target = Array.from({ length: 40 }, (_, i) => (i === 11 ? 'function knownSymbol() {' : `filler ${i + 1}`));
  const mk = (name, body) => {
    const f = path.join(tmp, name); fs.writeFileSync(f, body); return { file: f, text: body };
  };
  let ok = true;
  const check = (phase, cond, detail) => {
    if (cond) console.log(`✓ selftest[${phase}] — ${detail}`);
    else { console.error(`✗ selftest[${phase}] — ${detail}`); ok = false; }
  };

  // 1. dead — the symbol is nowhere in the target
  let r = audit([mk('dead.md', 'see `goneSymbol@12`')], target);
  check('dead', r.dead.length === 1 && !r.stale.length, 'a symbol absent from the target is DEAD');

  // 2. stale — resolves, but the cached number drifted
  r = audit([mk('stale.md', 'see `knownSymbol@31`')], target);
  check('stale', r.stale.length === 1 && !r.dead.length && r.stale[0].hits[0] === 12,
    'a resolvable symbol with a drifted number is STALE, not a failure');

  // 3. fresh — resolves at exactly the cached line
  r = audit([mk('fresh.md', 'see `knownSymbol@12`')], target);
  check('fresh', r.fresh.length === 1 && !r.stale.length && !r.dead.length,
    'a symbol at its cached line is FRESH');

  // 4. fix — rewrites the stale hint, leaves the dead one untouched
  const doc = mk('fix.md', 'a `knownSymbol@31` and a `goneSymbol@12`');
  const n = fix([doc], target);
  const after = fs.readFileSync(doc.file, 'utf8');
  check('fix', n === 1 && after.includes('`knownSymbol@12`') && after.includes('`goneSymbol@12`'),
    'stale hint refreshed to line 12; the dead anchor left alone (never guess)');

  // 5. boundary — a symbol that is merely a PREFIX or SUFFIX of the real one is dead.
  // Without this, renaming `XP_BY_TIER` → `XP_BY_TIER_RETIRED` would still "resolve".
  r = audit([mk('bound.md', 'a `knownSymbo@12` and a `nownSymbol@12`')], target);
  check('boundary', r.dead.length === 2 && !r.stale.length && !r.fresh.length,
    'a prefix/suffix of the real identifier does NOT resolve — a rename stays DEAD');

  // 6. placeholder — the docs must be able to SHOW the convention without --fix
  // re-pointing the example (the literal word "symbol" resolves in the real game file).
  const ph = mk('ph.md', 'write it as `symbol@1234`');
  r = audit([ph], target);
  const phFixed = (fix([ph], target), fs.readFileSync(ph.file, 'utf8'));
  check('placeholder', !r.dead.length && !r.stale.length && !r.fresh.length && phFixed.includes('`symbol@1234`'),
    'the documented `symbol@1234` example is neither audited nor rewritten');

  // 7. file-qualified — `path.js:symbol@N` resolves in THAT file, not the game HTML
  r = audit([mk('qual.md', 'see `src/js/wbapi-server.js:function seededNext@99`, '
    + 'and `js/no-such-file.js:whatever@99`')], target);
  check('qualified', r.stale.length === 1 && r.stale[0].hits.length === 1 && r.dead.length === 1,
    'resolved against src/js/wbapi-server.js (not the stand-in target); a missing file is DEAD');

  fs.rmSync(tmp, { recursive: true, force: true });
  return ok;
}

// ── main ──────────────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
if (argv.includes('--selftest')) process.exit(selftest() ? 0 : 1);

const lines = fs.readFileSync(HTML, 'utf8').split('\n');
const query = argv.find(a => !a.startsWith('--'));

if (query) {                                    // lookup mode — the grep -n replacement
  const t = targetFor(query, lines, new Map());
  const where = t.file || rel(HTML);
  const hits = resolve(t.lines, t.sym);
  if (!hits.length) { console.error(`✗ '${t.sym}' does not occur in ${where}`); process.exit(1); }
  console.log(`${hits.length} line(s) in ${where} contain '${t.sym}':\n`);
  for (const n of hits.slice(0, 20)) console.log(`  \`${query.replace(/@\d+$/, '')}@${n}\`  ${t.lines[n - 1].trim().slice(0, 100)}`);
  if (hits.length > 20) console.log(`  … and ${hits.length - 20} more`);
  process.exit(0);
}

const docs = docFiles().map(f => ({ file: f, text: fs.readFileSync(f, 'utf8') }));

if (argv.includes('--legacy')) {
  const rows = legacyCounts(docs);
  const total = rows.reduce((s, r) => s + r.count, 0);
  console.log(`${total} un-migrated bare line anchors (the \`NNNNN\` form) across ${rows.length} file(s):\n`);
  for (const r of rows) console.log(`  ${String(r.count).padStart(4)}  ${rel(r.file)}`);
  console.log('\n  Migrate one by naming what it points at:  `symbol@1234`  (then `npm run anchors:fix`).');
  console.log('  Closed ship records are HISTORY — annotate, do not rewrite (§DX-02c/§AUDIT-03m).');
  process.exit(0);
}

if (argv.includes('--fix')) {
  const n = fix(docs, lines);
  console.log(n ? `✓ refreshed ${n} stale line hint(s)` : '✓ no stale line hints to refresh');
}

const { dead, stale, generic, fresh } = audit(docs, lines);

if (stale.length) {
  console.warn(`⚠ ${stale.length} stale line hint(s) — the symbol resolves, the number drifted:`);
  for (const a of stale.slice(0, 12))
    console.warn(`    ${rel(a.file)}:${a.docLine}  \`${a.sym}@${a.cached}\` → ${a.hits[0]}`);
  if (stale.length > 12) console.warn(`    … and ${stale.length - 12} more`);
  console.warn('  Run `npm run anchors:fix` — hints are refreshable, and stale ones never fail this gate.\n');
}
if (generic.length) {
  console.warn(`⚠ ${generic.length} anchor(s) name a symbol with >25 matches — too generic to point anywhere:`);
  for (const a of generic.slice(0, 6)) console.warn(`    ${rel(a.file)}:${a.docLine}  \`${a.sym}\` (${a.hits.length} hits)`);
  console.warn('');
}
if (dead.length) {
  console.error(`✗ check:anchors — ${dead.length} doc anchor(s) name a symbol that is NOT in ${rel(HTML)}:\n`);
  for (const a of dead) console.error(`    ${rel(a.file)}:${a.docLine}  \`${a.sym}@${a.cached}\``);
  console.error('\n  The pointer is dead, not merely drifted — the symbol was renamed or removed and the');
  console.error('  doc still names it. Find the current name (`node scripts/resolve-anchors.js <symbol>`),');
  console.error('  fix the doc, then `npm run anchors:fix` to refresh the number.');
  process.exit(1);
}
console.log(`✓ check:anchors — ${fresh.length + stale.length} symbol anchor(s) across `
  + `${new Set([...fresh, ...stale].map(a => a.file)).size} doc(s) all resolve in ${rel(HTML)}`
  + (stale.length ? ` (${stale.length} hint(s) stale — run \`npm run anchors:fix\`)` : ''));
