// SPDX-License-Identifier: MIT — Copyright (c) 2026 Paul Richeson
// §DROP-01-FU — the d20 `LOOT_TABLE` stays deleted, and `_D100_TABLE`'s header stays generated.
//
// Why this test exists: the deletion shipped once already. `440eb5d` (2026-06-05 10:41)
// removed the array; `88d41d1`, three hours later, put it back under a commit subject about
// a smoke-test cleanup. It then stood unread for 82 days while three home docs certified it
// as removed. A deletion that has been reverted once is not guarded by having been made twice.
//
// The second half is the §DROP-01-FU(b) property: the comment block above `_D100_TABLE` in
// play.html is EMITTED by `serializeD100Table()` in src/js/wbapi-server.js, so any write to
// /api/loot re-emits it and an edit made in play.html survives exactly until the generator
// runs. Asserting both copies carry the same header is what makes that non-obvious fact fail
// loudly instead of silently reverting someone's work.
//
// Pure-node (no browser): a source-text invariant. Nothing is written.

const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const HTML = fs.readFileSync(path.join(ROOT, 'play.html'), 'utf8');
const SERVER = fs.readFileSync(path.join(ROOT, 'src', 'js', 'wbapi-server.js'), 'utf8');

const GENERATED_LINE = 'GENERATED by serializeD100Table() in src/js/wbapi-server.js';
const MAGIC_LINE = "A 'dagger' or 'mainweapon' row REQUIRES _magic";

test.describe('§DROP-01-FU — the retired loot table', () => {
  test('LOOT_TABLE is gone from play.html — 0 occurrences, not 0 readers', () => {
    expect(HTML.match(/LOOT_TABLE/g) || []).toHaveLength(0);
  });

  test('the live roller is _D100_TABLE, and it is what _rollD100Loot reads', () => {
    expect(HTML).toContain('const _D100_TABLE = [');
    expect(HTML).toContain('for (const row of _D100_TABLE)');
  });

  test("play.html's _D100_TABLE header is the serializer's output, not a hand-edit", () => {
    for (const line of [GENERATED_LINE, MAGIC_LINE]) {
      expect(SERVER).toContain(line);
      expect(HTML).toContain(line);
    }
  });

  test('the header tells the truth: the roller still accepts dagger and mainweapon rows', () => {
    expect(HTML).toContain("if (row._type === 'dagger')");
    expect(HTML).toContain("if (row._type === 'mainweapon')");
    expect(HTML).toContain('if (!_magicTierAllowed(row._magic)) continue;');
  });

  test('negative control — a reinstated declaration, and a header edited in one copy only, both fail', () => {
    const reinstated = HTML.replace('const _D100_TABLE = [', 'const LOOT_TABLE = [\n];\nconst _D100_TABLE = [');
    expect(reinstated.match(/LOOT_TABLE/g) || []).not.toHaveLength(0);
    const handEdited = HTML.replace(MAGIC_LINE, 'A dagger row needs nothing');
    expect(handEdited.includes(MAGIC_LINE) && SERVER.includes(MAGIC_LINE)).toBe(false);
  });
});
